# Generated by Django 3.2.9 on 2021-11-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restolax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_acc_info',
            name='black_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restolax.black_list'),
        ),
        migrations.AlterField(
            model_name='black_list',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restolax.users'),
        ),
    ]
